name: queuekit
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lint: ^2.3.0
  script_runner: ^0.7.3
  test: ^1.24.0

script_runner:
  scripts:
    - analyze: dart analyze
    - format: dart format --line-length 100 --fix lib && dart format --line-length 100 --fix test
